WIP: Migrate to MV3
Authenticator-Extension/Authenticator pull request #1009
Opened 2023-01-31 20:24 UTC by Sneezry

- [x] Move to `chrome.storage.session` to cache password
- [x] Move to `chrome.scripting` to inject scan QR script
- [x] Replace `content_security_policy` with `content_security_policy.extension_pages` or `content_security_policy.sandbox` as appropriate.
- [ ] Migrate LocalStorage to `chrome.storage.local`

2023-02-02 20:47 UTC, Sneezry commented
Some scenario test is still on the way, but the code should be ready for review.

2023-02-02 20:48 UTC, Sneezry commented
This PR only contains Chrome parts. Firefox and Edge MV3 migration should be in other PRs.

2023-02-02 20:54 UTC, Sneezry commented
@rebornix Chrome, Firefox, and Edge are starting to migrate to MV3, MV2 will stop working in the next few months. There are many breaking changes in MV3, Safari may also have some updates. Once this PR has been merged, the Safari build may be broken.

2023-02-05 02:49 UTC, mymindstorm commented
Just FYI, I might not be able to get to this until next Wednesday.

2023-02-21 03:32 UTC, mymindstorm commented
I'm getting 

```
/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mymindstorm/Projects/Authenticator-1/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mymindstorm/Projects/Authenticator-1/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/mymindstorm/Projects/Authenticator-1/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/mymindstorm/Projects/Authenticator-1/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/mymindstorm/Projects/Authenticator-1/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/home/mymindstorm/Projects/Authenticator-1/node_modules/ts-loader/dist/index.js:90:5)
    at successLoader (/home/mymindstorm/Projects/Authenticator-1/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/home/mymindstorm/Projects/Authenticator-1/node_modules/ts-loader/dist/index.js:22:12)
    at LOADER_EXECUTION (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/mymindstorm/Projects/Authenticator-1/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/mymindstorm/Projects/Authenticator-1/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/mymindstorm/Projects/Authenticator-1/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/mymindstorm/Projects/Authenticator-1/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

when building. It goes away with `export NODE_OPTIONS=--openssl-legacy-provider`.

 I think this might be fixed if we use a newer version of webpack. Would that be easy to do here?


---

The service worker isn't registering properly on my Chrome: `Service worker registration failed. Status code: 15`.

![image](https://user-images.githubusercontent.com/27789806/220240646-6f2ce98f-9a5d-457f-8cb4-957bf996180c.png)

---

Keyboard shortcuts seem to not be working due to manifest issue:

![Uploading image.png…]()

2023-02-21 03:41 UTC, Sneezry commented
Can you load this build locally?
[chrome.zip](https://github.com/Authenticator-Extension/Authenticator/files/10789323/chrome.zip)

2023-02-21 03:43 UTC, mymindstorm commented
That build has same issues with the service worker and keyboard commands.

2023-02-21 03:46 UTC, Sneezry commented
Interesting... It works fine on my machine though...

![image](https://user-images.githubusercontent.com/1621293/220242490-8e0dbd82-9afa-483d-b62b-1e09b59de843.png)

![image](https://user-images.githubusercontent.com/1621293/220242531-f1ca9d29-bc67-4728-ac96-e99b04c89066.png)

![image](https://user-images.githubusercontent.com/1621293/220242564-d99fe754-55a7-483d-97e9-3d7b66cf1b47.png)

2023-02-21 04:14 UTC, mymindstorm commented
Interesting, I'll investigate further this weekend. What is your chrome version?


-------- Original message --------
From: Zhe Li ***@***.***>
Date: 2/20/23 9:47 PM (GMT-06:00)
To: Authenticator-Extension/Authenticator ***@***.***>
Cc: Brendan Early ***@***.***>, Review requested ***@***.***>
Subject: Re: [Authenticator-Extension/Authenticator] Migrate to Chrome MV3 (PR #1009)


Interesting... It works fine on my machine though...

[image]<https://user-images.githubusercontent.com/1621293/220242490-8e0dbd82-9afa-483d-b62b-1e09b59de843.png>

[image]<https://user-images.githubusercontent.com/1621293/220242531-f1ca9d29-bc67-4728-ac96-e99b04c89066.png>

[image]<https://user-images.githubusercontent.com/1621293/220242564-d99fe754-55a7-483d-97e9-3d7b66cf1b47.png>

—
Reply to this email directly, view it on GitHub<https://github.com/Authenticator-Extension/Authenticator/pull/1009#issuecomment-1437819555>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGUAT3TEG4BOBV3HDW2IS7DWYQ3DZANCNFSM6AAAAAAUM4FOEQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-02-21 04:21 UTC, mymindstorm commented
oops, I see that you've attached it.

2023-03-09 04:50 UTC, Sneezry commented
I might find the root cause of the service work register issue. 

> Lots of API inside chrome are present only if your extension's manifest.json lists its associated permission name in "permissions" or in a special key
> https://stackoverflow.com/a/73789284

The contextMenu is in optional permission, which means `chrome.contextMenu` should be undefined before the permission granted.

We can move it to required permission since I see no security risk about that.

@mymindstorm do you have any concern?

2023-03-09 04:51 UTC, mymindstorm commented
Sorry for the lateness on this. I will get to it as soon as I can.

2023-03-09 04:51 UTC, mymindstorm commented
I agree, I don't see a security concern there.

2023-04-02 19:23 UTC, mymindstorm commented
I think I've resolved most of the issues I found. Please make sure to test on your end too to make sure I didn't miss anything.

2023-04-02 20:03 UTC, mymindstorm commented
I am leaving the tests broken, I ran out of time to fix them.

2023-04-10 03:35 UTC, Sneezry commented
> I think I've resolved most of the issues I found. Please make sure to test on your end too to make sure I didn't miss anything.

Awesome! It works w/o problems on my side.

2023-12-02 03:01 UTC, DNin01 commented on manifests/manifest-chrome.json
>      "offline_enabled": true,
I can't find any information that suggests that `offline_enabled` is still supported by Manifest V3. Compare these pages:
https://developer.chrome.com/docs/extensions/mv2/manifest/
https://developer.chrome.com/docs/extensions/mv3/manifest/

[The page for this property on MDN Web Docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/offline_enabled) also lists the supported manifest version as 2 only.

2023-12-04 03:43 UTC, Sneezry commented on manifests/manifest-chrome.json
>      "offline_enabled": true,
Thanks for the information.

2024-01-02 04:56 UTC, mymindstorm commented
I spent a few hours working on tests. I had to disable the UI ones until I have more time to work out the kinks of MV3 disallowing all unsafe-eval, but it is better than it was previously.

2024-02-29 08:11 UTC, Sneezry commented
Firefox should now be operational. However, end-to-end testing has not yet been completed.

2024-03-08 14:38 UTC, WofWca commented
Hey! So, the extension seems to be working alright on Manifest V3, it's only tests (i.e. non-production code) that are missing? Am I reading this correctly?

2024-03-08 23:51 UTC, Sneezry commented
> Hey! So, the extension seems to be working alright on Manifest V3, it's only tests (i.e. non-production code) that are missing? Am I reading this correctly?

The end-to-end test is not completed. If all tests pass, we can deliver it to the public.

2024-03-15 23:31 UTC, mymindstorm commented
Tests work again! We lost the ability for code coverage reporting, but that was half broken due to vue anyway.

![image](https://github.com/Authenticator-Extension/Authenticator/assets/27789806/927e5f15-e3a4-4239-88c5-fb910a1a193c)

2024-03-18 02:02 UTC, mymindstorm requested changes
I really don't like how `LocalStorage` works. 

 - Putting it as a global everywhere makes it easy to misuse (e.g. forget to load/store data from/to `chrome.storage` again). This should all be hidden behind a class. It's too easy to make mistakes with the current way.
 - We should name is something more descriptive, like `userSettings`
 - We know exactly what should be in `LocalStorage`/`userSettings`. There should be an interface for it instead of `any`.

For example, something like:

```ts
// UserSettings.d.ts
declare type StorageLocation = "sync" | "local";

interface UserSettings {
    storageLocation?: StorageLocation;
}

// LocalUserSettings.ts
export class LocalUserSettings {
  static async getUserSettings(): Promise<UserSettings> {
    return (await chrome.storage.local.get("userSettings"))?.userSettings || {};
  }

  static async setUserSettings(userSettings: UserSettings) {
    await chrome.storage.local.set({ userSettings });
  }
}
```

2024-03-18 02:02 UTC, mymindstorm commented on src/models/storage.ts
>    // eslint-disable-next-line @typescript-eslint/no-explicit-any
remove these comments

2024-03-18 02:02 UTC, mymindstorm commented on src/models/storage.ts
>      // eslint-disable-next-line @typescript-eslint/no-explicit-any
remove this comment

2024-03-18 02:05 UTC, mymindstorm commented
Also, the migration for localStorage broke in Firefox. Will investigate when I have more time.

2024-03-18 04:31 UTC, Sneezry commented
> I really don't like how `LocalStorage` works.
> 
> * Putting it as a global everywhere makes it easy to misuse (e.g. forget to load/store data from/to `chrome.storage` again). This should all be hidden behind a class. It's too easy to make mistakes with the current way.
> * Using the global var as a sort-of cache introduces the possibility of race conditions
> * We should name is something more descriptive, like `userSettings`
> * We know exactly what should be in `LocalStorage`/`userSettings`. There should be an interface for it instead of `any`.
> 
> For example, something like:
> 
> ```ts
> // UserSettings.d.ts
> declare type StorageLocation = "sync" | "local";
> 
> interface UserSettings {
>     storageLocation?: StorageLocation;
> }
> 
> // LocalUserSettings.ts
> export class LocalUserSettings {
>   static async getUserSettings(): Promise<UserSettings> {
>     return (await chrome.storage.local.get("userSettings"))?.userSettings || {};
>   }
> 
>   static async setUserSettings(userSettings: UserSettings) {
>     let mergedSettings = await getUserSettings();
>     Object.assign(mergedSettings, userSettings);
>     await chrome.storage.local.set({ userSettings: mergedSettings });
>   }
> }
> ```
> 
> What are your thoughts on this?

That makes sense. I will update the code later.

2024-03-18 04:50 UTC, mymindstorm commented
Ok. I will be unavailable for the next week and a half, but can help out after that.

2024-05-13 08:53 UTC, Sneezry commented
@mymindstorm I have updated the PR. Let's complete this PR before end of the next week (5/26).

2024-05-20 04:46 UTC, Sneezry commented
> Also, the migration for localStorage broke in Firefox. Will investigate when I have more time.

I didn't meet any error when migrating from MV2. Could you test the latest code to verify if the issue has been resolved?

2024-05-20 12:45 UTC, mymindstorm commented
Sure. I've been sick since last week so it might take me some time to get to.


-------- Original message --------
From: Zhe Li ***@***.***>
Date: 5/19/24 11:47 PM (GMT-06:00)
To: Authenticator-Extension/Authenticator ***@***.***>
Cc: Brendan Early ***@***.***>, Mention ***@***.***>
Subject: Re: [Authenticator-Extension/Authenticator] Migrate to MV3 (Chrome, Firefox, Edge) (PR #1009)


Also, the migration for localStorage broke in Firefox. Will investigate when I have more time.

I didn't meet any error when migrating from MV2. Could you test the latest code to verify if the issue has been resolved?

—
Reply to this email directly, view it on GitHub<https://github.com/Authenticator-Extension/Authenticator/pull/1009#issuecomment-2119659227>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGUAT3QA5A42QZRE66CI6GTZDF55BAVCNFSM6AAAAAAUM4FOESVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJZGY2TSMRSG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-20 15:56 UTC, Sneezry commented
Oh, take care and recover soon!

Brendan Early ***@***.***>于2024年5月20日 周一20:46写道：

> Sure. I've been sick since last week so it might take me some time to get
> to.
>
>
> -------- Original message --------
> From: Zhe Li ***@***.***>
> Date: 5/19/24 11:47 PM (GMT-06:00)
> To: Authenticator-Extension/Authenticator ***@***.***>
> Cc: Brendan Early ***@***.***>, Mention ***@***.***>
> Subject: Re: [Authenticator-Extension/Authenticator] Migrate to MV3
> (Chrome, Firefox, Edge) (PR #1009)
>
>
> Also, the migration for localStorage broke in Firefox. Will investigate
> when I have more time.
>
> I didn't meet any error when migrating from MV2. Could you test the latest
> code to verify if the issue has been resolved?
>
> —
> Reply to this email directly, view it on GitHub<
> https://github.com/Authenticator-Extension/Authenticator/pull/1009#issuecomment-2119659227>,
> or unsubscribe<
> https://github.com/notifications/unsubscribe-auth/AGUAT3QA5A42QZRE66CI6GTZDF55BAVCNFSM6AAAAAAUM4FOESVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJZGY2TSMRSG4>.
>
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Authenticator-Extension/Authenticator/pull/1009#issuecomment-2120392085>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAML2LK6LWI4FEUZLYDRO4TZDHWBJAVCNFSM6AAAAAAUM4FOESVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRQGM4TEMBYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-24 12:21 UTC, Sneezry commented
Considering Google is required all extensions to migrate to MV3 by June, and leaving a week for CWS review, I will complete this PR by 5/26 anyway.

2024-05-26 22:07 UTC, mymindstorm commented
Just FYI, starting to work on this. Will probably push something within 3-6 hours.

2024-05-26 23:30 UTC, mymindstorm approved these changes
From what I've seen it appears to work fine, outside of that crash I found.

2024-05-27 05:36 UTC, merged