fix add account issue
Authenticator-Extension/Authenticator pull request #1264
Opened 2024-08-21 12:09 UTC by Sneezry

Fix https://github.com/Authenticator-Extension/Authenticator/issues/1262

2024-08-21 17:17 UTC, mymindstorm commented on src/models/otp.ts
> +    encryption?: EncryptionInterface | Map<string, EncryptionInterface>
This should just be a `Map<string, EncryptionInterface>`, the only place we need to have a case for `EncryptionInterface` is before migration logic runs.

2024-08-21 17:19 UTC, mymindstorm commented on src/models/otp.ts
> +          this.encryption = encryption.get(key);
Use `state.accounts.defaultEncryption` instead of a loop

2024-08-21 17:22 UTC, mymindstorm requested changes
Please ignore previous comments.

Instead of making OTPEntry have multiple encryptions (we need to maintain a 1:1 relationship between an OTPEntry and an encryption), make 

https://github.com/Authenticator-Extension/Authenticator/blob/dev/src/components/Popup/AddAccountPage.vue#L131 

pass `state.accounts.defaultEncryption` instead.

2024-08-21 22:37 UTC, Sneezry commented
Updated

2024-08-22 01:52 UTC, mymindstorm approved these changes

2024-08-22 05:09 UTC, merged