fix import unencrypted backup file issue, add auto paste code to input box
Authenticator-Extension/Authenticator pull request #143
Opened 2018-06-08 05:57 UTC by Sneezry

2018-06-09 01:45 UTC, mymindstorm commented
Firefox doesn't like async permission requests:
```
Error: permissions.request may only be called from a user input handler
```

Is it a good idea to just send the code even though it won't be used? Would it be better to query if a 2fa field is there and then send the code?

2018-06-10 11:02 UTC, Sneezry commented
It should work now

2018-06-10 21:14 UTC, mymindstorm requested changes

2018-06-10 21:14 UTC, mymindstorm commented on src/content.ts
> +  const identities = ['2fa', 'otp', 'authenticator', 'factor'];
I've seen some sites use `code` too

2018-06-10 21:14 UTC, mymindstorm commented on src/content.ts
> +  firstInputBox.value = code;
This is destructive to data already in the input box. Either remove this section and let user paste code, or check if data is already in input box. This also goes for line 193

2018-06-11 02:57 UTC, mymindstorm approved these changes

2018-06-11 03:16 UTC, mymindstorm commented
Not exactly sure if it's ok to insert the code to a page no matter what, it seems to be against [Mozilla policy](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#No_Surprises).

Specifically:

> Makes unexpected changes to the browser or web content

> All changes must be “opt-in”, meaning the user has to take non-default action to enact the change. Changes that prompt users via the permissions system don’t require an additional opt-in.

To be on the safe side it might be necessary to add a setting to turn this on.

2018-06-11 06:46 UTC, Sneezry commented
Wondering how does 1Password do on Firefox. It will fill username and password on web page on Chrome by one click.

2018-06-12 04:12 UTC, mymindstorm commented
> Users should be able to easily discern what the functionality of your add-on is and not be presented with unexpected user experiences after installing it.

> “Unexpected” features are those that are unrelated to the add-on’s primary function, and are not likely from the add-on name or description to be expected by a user installing that add-on.

A password manager's browser extension's primary function is to read passwords from and insert passwords  to form fields and send them back to the main application. Authenticator's main function is to store and display 2fa codes. 

Even if you successfully argue that it's related to Authenticator's primary function, it's not made apparent anywhere that clicking on a code will insert it into the current page. 1Password and other password managers' browser extensions usually show a selector box next to password input to select an account making it less unexpected.

2018-06-12 04:53 UTC, Sneezry commented
How about just disable auto fill for Firefox currently?

2018-06-12 05:50 UTC, mymindstorm commented
All that's needed for this to be compliant is an opt-in checkbox. If you merge this as it is now, I can add a checkbox for it before release.

2018-06-12 05:51 UTC, Sneezry commented
Cool, then I merge it.

2018-06-12 05:51 UTC, merged