Add security key support
Authenticator-Extension/Authenticator pull request #496
Opened 2020-06-08 15:43 UTC by Sneezry

2020-06-08 21:40 UTC, mymindstorm requested changes
Please ignore all the other review comments and the TODOs below for now.

This just encrypts the user's password directly with the credential id. The credential id isn't secure (I.e. we can't guarantee that it's random data). We can sign and verify data, but webauthn does not provide any way to securely encrypt data (it looks as if only client-server flows were considered). It seems to be possible using native code, but that would probably be too complicated from a user's perspective. I found lots of good discussion on encryption using fido keys below. It looks like our best bet would be to propose changes to the WebAuthn API...

https://groups.google.com/a/fidoalliance.org/d/topic/fido-dev/kMe6Kb4GCpU/discussion
https://bugs.chromium.org/p/chromium/issues/detail?id=1023225#c7
https://bugs.chromium.org/p/chromium/issues/detail?id=1023225#c12
https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#sctn-hmac-secret-extension


<details>
<summary>Old review comments</summary>

- WebAuthn supports linux
- check if webauthn is supported on the browser before showing the button https://caniuse.com/#search=webauthn / MDN
- ~~Can we store the `securityTokenEncryptedKey` in `key` so that it is stored in backups? How will backups work with this in general~~

</details>

2020-06-08 21:40 UTC, mymindstorm commented on _locales/en/messages.json
> +        "message": "Operation failed."
Crowdin is going to flood my email again :(

use `updateFailure`

2020-06-08 21:40 UTC, mymindstorm commented on _locales/en/messages.json
> +        "message": "You must set a passphrase before enable security key."
```suggestion
        "message": "You must set a password before adding a security key."
```

2020-06-08 21:40 UTC, mymindstorm commented on _locales/en/messages.json
> +        "message": "Security key enabled."
```suggestion
        "message": "Security key added."
```

2020-06-08 21:40 UTC, mymindstorm commented on src/components/Popup/EnterPasswordPage.vue
> +      return !!localStorage.securityTokenEncryptedKey;
`!!`?

2020-06-08 21:40 UTC, mymindstorm commented on _locales/en/messages.json
> +        "message": "You have already enabled security key, do you want to continue?"
```suggestion
        "message": "Your old security key will not work, are you sure you want to continue?"
```

2020-06-08 21:40 UTC, mymindstorm commented on _locales/en/messages.json
> +        "message": "Update passphrase will reset security key, do you want to continue?"
```suggestion
        "message": This action will also remove your security key, do you want to continue?"
```

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +          localStorage.removeItem("securityTokenEncryptedKey");
There is no older version that uses this key?

2020-06-08 21:40 UTC, mymindstorm commented on svg/windows-hello.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45 45" class="feature-icon-svgs x-hidden-focus"><path d="M22.38 34a15.68 15.68 0 01-3.99-.516 16.574 16.574 0 01-7.01-3.807c-1-.912-1.847-1.943-2.
Do we need to add lines in the license file for these?

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +                id: chrome.runtime.id,
This is different between browsers. Will this break backups between Chrome <=> Firefox if enabled?

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +              rp: {
We can add an icon! https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/rp

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +                name: "Authenticator",
Is it possible to remove the name / displayname since we don't actually know any of this info?

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +                id: new Uint8Array(16)
Is it really ok for us to just have blank ids?

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +              challenge: new Uint8Array(16),
this should have some random data. we should verify that the key is working and response is signed properly

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +                { type: "public-key", alg: -257 },
This is deprecated

https://www.iana.org/assignments/cose/cose.xhtml#algorithms

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +                { type: "public-key", alg: -258 },
Not recommended

https://www.iana.org/assignments/cose/cose.xhtml#algorithms

2020-06-08 21:40 UTC, mymindstorm commented on src/store/Accounts.ts
> +                { type: "public-key", alg: -259 },
Not recommended

https://www.iana.org/assignments/cose/cose.xhtml#algorithms

2020-06-08 21:49 UTC, mymindstorm commented
There is already a draft: https://github.com/w3c/webauthn/pull/1424

2020-06-09 14:04 UTC, Sneezry commented
> This just encrypts the user's password directly with the credential id.
Correct. Credential id is generated with the hardware, and it's value can be gotten only when the user touch the figure scanner or type the PIN. Though WebAuthn doesn't provide a way to encrypt data, but we also never expose the credential id, so I don't think there is a risk.

> It seems to be possible using native code
No, we shouldn't touch native code. It's beyond our scope. And we can't maintain native code for all platforms.

2020-06-09 19:59 UTC, mymindstorm commented
> Correct. Credential id is generated with the hardware, and it's value can be gotten only when the user touch the figure scanner or type the PIN. 

Unfortunately, this is not the case. There is nothing preventing a vendor from making the id a hash of publicly known information or a serial that is incremented every time a new credential is generated. In either case an attacker would be able to get plaintext user password with current implementation.

The below email thread is a good example of a security key vendor about to do that. It's worth noting that the Yubico dev says that it's completely up to the vendor how this is implemented.

https://groups.google.com/a/fidoalliance.org/d/topic/fido-dev/5mwvgna3RKc/discussion

Below is a link to the spec, the "key handle" is the rawId. Same as above, there is nothing explicitly preventing an easily guessable id.

https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-raw-message-formats-v1.1-id-20160915.html#registration-response-message-success

> Though WebAuthn doesn't provide a way to encrypt data, but we also never expose the credential id, so I don't think there is a risk.

As I understand it, normally you are supposed to store the credential id somewhere [and use it when calling credentials.get](https://developer.mozilla.org/en-US/docs/Web/API//allowCredentials). Without storing the id, there is no guarantee that we will get the same credential if the user ever regenerates their key.

I recently found that some browsers already have an undocumented hmacCreateSecret extension we could use to do this in a secure way. It seems that it was made specifically for Windows Hello support. What do you think about trying to use that?

https://groups.google.com/a/fidoalliance.org/d/topic/fido-dev/SX6AoLAoOx8/discussion

2020-06-10 13:23 UTC, Sneezry commented
> Unfortunately, this is not the case...

There isn't a standard for how to generate credential id hash, so the attacker also has no idea how to generate the credential id with RP id. Also, user id is a random number that only use once when we register the device. We don't store user id, either. The way we use webauthn here is very different from how it is designed. We don't store anything but the encrypted secret with the credential id. The only thing can be known without customer's permission is RP id.

> As I understand it, normally you are supposed to store the credential id somewhere...

The way we use webauthn here is very different from how it is designed, we don't store the credential id. The credential id is stored in the hardware security chip. Instead of using `allowCredentials`, which requires the credential id, we just list all credentials match our RP id, and ask customer to choose the correct one - even if the customer has the correct PIN, if the chosen credential is not the one to encrypt the password, decyption will fail (for example, customer use Windows Hello to encrypt data, however, chose another hardward security token to decrypt, will meet an error).

---

I understand webauthn is not designed for encryption. However, if the credential id cannot be read without customer's permission, it can be a good key to protect the data.

2020-06-10 13:28 UTC, Sneezry commented on src/components/Popup/EnterPasswordPage.vue
> +      return !!localStorage.securityTokenEncryptedKey;
`!!localStorage.securityTokenEncryptedKey` always has bool value

2020-06-10 13:30 UTC, Sneezry commented on src/store/Accounts.ts
> +                id: new Uint8Array(16)
I thought it will be some random chars without setting a value just like C language. I will update to use a random string.

2020-06-10 13:32 UTC, Sneezry commented on src/store/Accounts.ts
> +              challenge: new Uint8Array(16),
We don't care about the credential, we are only intereted in credential id

2020-06-10 13:33 UTC, Sneezry commented on src/store/Accounts.ts
> +                { type: "public-key", alg: -257 },
It's the only supported algorithm for Windows Hello. https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication

2020-06-13 22:28 UTC, mymindstorm commented
I have thought about this for the past few days, and I am still not comfortable with this. I do not think that using a standard in a non-intended way is a smart move when dealing with sensitive user data. We do not have any guarantees nor can we make any assumptions about the entropy of the key handle.

If you still want to move forward with this and keep the same encryption scheme, we should send an email to the fido-dev mailing list and get an opinion from the implementors and developers of the spec.

2020-06-14 11:28 UTC, Sneezry commented
> I do not think that using a standard in a non-intended way is a smart move when dealing with sensitive user data.

I totally agree with you.

> If you still want to move forward with this and keep the same encryption scheme...

We have no need to move forward in such a hurry. This is not an urgent or required feature. I just publish it for review and discussion. Let's make everything reliable and ready before ship it.

2020-07-01 15:28 UTC, Sneezry commented
>I know that HMAC secret description is misleading, but you can not use it for "encryption". The extension is generating HMAC key, scoped to the credential. During GetAssertion you can provide HMAC secret extensions with one or two salts, and you will be given HMAC for each of the salts. Platform can leverage that to do offline authentication by rolling salts.
>
>And yes, browser are not supporting it.
>
>Pleaser read HMAC secret extension definition properly https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#sctn-hmac-secret-extension.

https://groups.google.com/a/fidoalliance.org/d/msg/fido-dev/kMe6Kb4GCpU/EZjN19qhBQAJ

It seems HMAC extension is not what we want

2020-07-02 17:54 UTC, mymindstorm commented
I missed that, I was mistaken. After re-reading that thread, it is clear that we should not be using WebAuthn for encryption at all.

2020-07-03 13:20 UTC, Sneezry commented
Correct. We have to wait for new web standard for data encryption scenario. I'm closing this PR, and keep an eye on the change in W3C org.

2020-07-03 13:20 UTC, closed without merging